Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
  
    #This configuration forwards requests made to port 8080 on your host machine to port 80 on the Vagrant guest machine
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    # Optional: If you want Vagrant to ask which interface to bridge each
    # time it starts up the VM, remove the bridge option:
    # config.vm.network "public_network"
  end
  